import Link from "next/link";
import { ArrowUpRight, Instagram, Linkedin, Mail, MapPin, Twitter, Youtube } from "lucide-react";
import { Logo } from "./Logo";

interface FooterLink { label: string; href: string; external?: boolean; }
const columns: { title: string; links: FooterLink[] }[] = [
  { title: "Governance", links: [{ label: "Right to Information (RTI)", href: "https://www.isro.gov.in/RTI.html", external: true }, { label: "Citizen Charter", href: "https://www.isro.gov.in/citizencharter.html", external: true }, { label: "Vigilance", href: "https://www.isro.gov.in/vigilance.html", external: true }, { label: "Internal Complaints", href: "https://www.isro.gov.in/contact.html", external: true }] },
  { title: "Data & Services", links: [{ label: "Bhuvan", href: "https://bhuvan.nrsc.gov.in/", external: true }, { label: "MOSDAC", href: "https://mosdac.gov.in/", external: true }, { label: "Bhoonidhi", href: "https://bhoonidhi.nrsc.gov.in/", external: true }, { label: "Launch Services (NSIL)", href: "https://www.isro.gov.in/launchservices.html", external: true }] },
  { title: "Engagement", links: [{ label: "Tenders & Procurement", href: "https://www.isro.gov.in/Tenders.html", external: true }, { label: "Student Satellites", href: "https://www.isro.gov.in/Student_Program_Satellite.html", external: true }, { label: "YUVIKA", href: "https://www.isro.gov.in/YUVIKA.html", external: true }, { label: "Outreach", href: "https://www.isro.gov.in/Outreach.html", external: true }] }
];

function FooterLinkItem({ link }: { link: FooterLink }) {
  const classes = "inline-flex items-center gap-1 transition-colors hover:text-white";
  return link.external ? <a href={link.href} target="_blank" rel="noopener noreferrer" className={classes}>{link.label}<ArrowUpRight size={12} /></a> : <Link href={link.href} className={classes}>{link.label}</Link>;
}

export function Footer() { return <footer id="footer" className="border-t border-white/10 bg-[#0A0A0A] px-6 pb-8 pt-20 lg:px-10 lg:pt-28"><div className="mx-auto max-w-[1440px]"><div className="grid grid-cols-1 gap-14 sm:grid-cols-2 lg:grid-cols-4 lg:gap-10"><div><Logo /><p className="mt-8 max-w-xs text-sm leading-7 text-neutral-400">Indian Space Research Organisation · Department of Space, Government of India.</p><div className="mt-8 flex gap-4 text-neutral-400"><a href="https://www.instagram.com/isro.dos/" target="_blank" rel="noopener noreferrer" aria-label="ISRO Instagram" className="hover:text-white"><Instagram size={17} /></a><a href="https://x.com/isro" target="_blank" rel="noopener noreferrer" aria-label="ISRO X" className="hover:text-white"><Twitter size={17} /></a><a href="https://www.youtube.com/channel/UCw5hEVOTfz_AfzsNFWyNlNg" target="_blank" rel="noopener noreferrer" aria-label="ISRO YouTube" className="hover:text-white"><Youtube size={17} /></a><a href="https://www.linkedin.com/company/indian-space-research-organisation/" target="_blank" rel="noopener noreferrer" aria-label="ISRO LinkedIn" className="hover:text-white"><Linkedin size={17} /></a></div></div>{columns.map((column) => <div key={column.title}><h3 className="mb-6 text-[10px] font-bold uppercase tracking-[.25em] text-ember">{column.title}</h3><div className="flex flex-col items-start gap-4 text-sm text-neutral-400">{column.links.map((link) => <FooterLinkItem key={link.label} link={link} />)}</div></div>)}<div><h3 className="mb-6 text-[10px] font-bold uppercase tracking-[.25em] text-ember">Headquarters</h3><p className="flex gap-3 text-sm leading-6 text-neutral-400"><MapPin size={17} className="mt-1 shrink-0 text-white/50" /><span>Antariksh Bhavan<br />New BEL Road<br />Bengaluru 560094<br />Karnataka, India</span></p><a href="mailto:contactus@isro.gov.in" className="mt-5 flex items-center gap-3 text-sm text-neutral-400 hover:text-white"><Mail size={16} className="text-white/50" />contactus@isro.gov.in</a><a href="https://www.isro.gov.in/" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-1 text-[10px] uppercase tracking-[.16em] text-white/55 hover:text-white">Press Media Kit <ArrowUpRight size={12} /></a></div></div><div className="mt-20 flex flex-col justify-between gap-4 border-t border-white/10 pt-6 text-[10px] uppercase tracking-[.18em] text-neutral-500 sm:flex-row"><span>© 2026 ISRO · Government of India</span><div className="flex gap-5"><Link href="/" className="hover:text-white">Privacy Policy</Link><Link href="/" className="hover:text-white">Terms of Use</Link></div></div></div></footer>; }
