"use client";

import { ChevronDown } from "lucide-react";
import { motion } from "framer-motion";
import Image from "next/image";
import { isroImages } from "@/src/constants/images";

export function GaganyaanHero() {
  return <section className="relative flex min-h-screen items-center overflow-hidden bg-black px-6 pb-16 pt-40 lg:px-10"><Image src={isroImages.gaganyaanTvD1Launch} alt="Gaganyaan TV-D1 launch vehicle" fill priority sizes="100vw" className="object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/40 to-transparent" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_45%,rgba(255,92,53,.16),transparent_22%),linear-gradient(120deg,#02020266_8%,#0b111877_52%,#04040488)]" /><div className="absolute inset-0 opacity-40 bg-[linear-gradient(rgba(255,255,255,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.04)_1px,transparent_1px)] bg-[size:80px_80px]" /><motion.div initial={{ scale: .8, opacity: 0 }} animate={{ scale: 1, opacity: .9 }} transition={{ duration: 2, ease: "easeOut" }} className="absolute right-[12%] top-[25%] h-[32vw] w-[32vw] max-h-[520px] max-w-[520px] rounded-full border border-orange-200/20 shadow-[0_0_100px_rgba(255,92,53,.15)]"><div className="absolute inset-[8%] rounded-full border border-white/10" /><div className="absolute left-1/2 top-1/2 h-[18%] w-[18%] -translate-x-1/2 -translate-y-1/2 rounded-full bg-gradient-to-br from-orange-200/70 via-ember to-[#7c2615] shadow-[0_0_60px_rgba(255,92,53,.65)]" /><div className="absolute left-[8%] top-1/2 h-px w-[84%] -rotate-[18deg] bg-orange-200/25" /></motion.div><div className="relative mx-auto w-full max-w-[1440px]"><motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }}><p className="mb-7 text-[10px] font-bold uppercase tracking-[.35em] text-ember">India’s human spaceflight programme</p><h1 className="max-w-5xl text-[clamp(4rem,13vw,12.5rem)] font-bold uppercase leading-[.76] tracking-tighter text-white">Gaganyaan</h1><p className="mt-10 max-w-sm text-sm leading-7 text-white/55 md:text-base">A human-rated spacecraft. A three-day mission. A new chapter in India’s journey beyond Earth.</p></motion.div><motion.div animate={{ y: [0, 8, 0] }} transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-[-18vh] left-0 flex items-center gap-3 text-[10px] uppercase tracking-[.28em] text-white/50"><ChevronDown size={17} className="text-ember" />Scroll to explore</motion.div></div></section>;
}
